'use strict';
document.body.classList.add('js');
const nav=document.querySelector('#nav'),menu=document.querySelector('.menu');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
const chapters=[
['Un registro no es una factura de impuestos.','El RUT permite identificar, ubicar y clasificar sujetos de obligaciones administradas por la DIAN. Empieza por entender las responsabilidades que figuran en él.','¿Qué información de mi registro debo revisar?','https://www.dian.gov.co/tramitesservicios/tramites-y-servicios/tributarios/Paginas/RUT.aspx'],
['Una compra empieza por su concepto.','Antes de suponer un tratamiento de IVA, identifica la operación y consulta sus reglas. No todas las compras o servicios tienen la misma condición.','¿Qué estoy comprando y qué tratamiento corresponde?','https://www.dian.gov.co/'],
['El territorio forma parte de la pregunta.','El ICA se relaciona con actividades industriales, comerciales y de servicios. Consulta la autoridad competente y las reglas locales: Bogotá es una referencia, no una regla nacional.','¿Qué entidad territorial debo consultar?','https://www.haciendabogota.gov.co/es/impuestos/impuesto-de-industria-y-comercio-ica'],
['El período y la presentación son dos pistas.','Identifica el período al que pertenece la información y verifica el calendario aplicable en la fuente oficial. No uses una fecha de otro año o de otra obligación.','¿A qué período corresponde y dónde verifico su calendario?','https://www.dian.gov.co/']
];
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{const index=Number(button.dataset.page),chapter=chapters[index];document.querySelectorAll('[data-page]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active));});document.querySelector('#page-number').textContent='PÁGINA '+String(index+1).padStart(2,'0');document.querySelector('#page-title').textContent=chapter[0];document.querySelector('#page-copy').textContent=chapter[1];document.querySelector('#page-question').textContent=chapter[2];document.querySelector('#page-source').href=chapter[3];}));
const quiz=[
{question:'Registro que identifica, ubica y clasifica sujetos de obligaciones administradas por la DIAN.',options:['RUT','ICA','Retención'],correct:0,explanation:'El RUT es el registro. Consulta su información y las responsabilidades que figuran en él.'},
{question:'Mecanismo de recaudo anticipado que puede practicarse en un pago.',options:['Jurisdicción','Retención','RUT'],correct:1,explanation:'La retención es un mecanismo de recaudo anticipado. Revisa el concepto y el soporte del pago.'},
{question:'Pista que te ayuda a ubicar la autoridad competente para una obligación local.',options:['Color de la factura','Nombre del navegador','Jurisdicción'],correct:2,explanation:'La jurisdicción es el ámbito territorial relevante. Las reglas locales deben verificarse con la entidad competente.'},
{question:'¿Dónde conviene verificar el calendario aplicable a tu obligación?',options:['En cualquier ejemplo de internet','En la fuente oficial competente','En un calendario de otro año'],correct:1,explanation:'Consulta la fuente oficial del impuesto, territorio y período que correspondan. Un ejemplo no reemplaza esa verificación.'}
];
let current=0,score=0,answered=false;
const question=document.querySelector('#question'),answers=document.querySelector('#answers'),feedback=document.querySelector('#feedback'),next=document.querySelector('#next');
function renderQuestion(){answered=false;question.textContent=quiz[current].question;document.querySelector('#progress').textContent='PREGUNTA '+(current+1)+' DE '+quiz.length;document.querySelector('#score').textContent=score+' '+(score===1?'acierto':'aciertos');feedback.hidden=true;next.hidden=true;answers.replaceChildren();quiz[current].options.forEach((label,index)=>{const button=document.createElement('button');button.textContent=label;button.addEventListener('click',()=>choose(index,button));answers.append(button);});}
function choose(index,button){if(answered)return;answered=true;const correct=index===quiz[current].correct;if(correct)score++;answers.querySelectorAll('button').forEach(item=>{item.disabled=true;});button.classList.add('chosen');feedback.textContent=(correct?'¡Bien conectado! ':'La respuesta es «'+quiz[current].options[quiz[current].correct]+'». ')+quiz[current].explanation;feedback.hidden=false;document.querySelector('#score').textContent=score+' '+(score===1?'acierto':'aciertos');next.textContent=current===quiz.length-1?'Ver mi recorrido →':'Siguiente pregunta →';next.hidden=false;}
next.addEventListener('click',()=>{if(!answered)return;if(current<quiz.length-1){current++;renderQuestion();answers.querySelector('button').focus();}else{question.textContent='Terminaste el recorrido: '+score+' de '+quiz.length+' aciertos.';document.querySelector('#progress').textContent='RECORRIDO COMPLETO';answers.replaceChildren();feedback.textContent='Aprender no es acertar todo a la primera. Revisa el cuaderno y continúa en las fuentes oficiales.';next.hidden=true;document.querySelector('#restart').focus();}});
document.querySelector('#restart').addEventListener('click',()=>{current=0;score=0;renderQuestion();answers.querySelector('button').focus();});
renderQuestion();
